import { Md } from './Md';
import { parseDirectives, processInlineFileRefs } from '../lib/parseDirectives';
import { InlineDiff } from './InlineDiff';
import { InlineCode } from './InlineCode';
import { FilePill } from './FilePill';
import { Callout } from './Callout';
import type { Section, FileContent } from '../api';

interface SectionRendererProps {
  section: Section;
  files: Record<string, FileContent>;
  index: number;
}

export function SectionRenderer({ section, files, index }: SectionRendererProps) {
  const segments = parseDirectives(section.body);

  return (
    <section
      id={`section-${index}`}
      data-section-index={index}
      className="mb-16"
    >
      <h2 className="text-[1.6rem] font-semibold text-[var(--text-bright)] mb-8 pb-4 border-b border-[var(--border)] tracking-tight leading-tight">
        {section.title}
      </h2>

      {segments.map((segment, i) => {
        switch (segment.type) {
          case 'markdown':
            return (
              <div key={i} className="cruise-markdown">
                <Md
                  components={{
                    a: ({ href, children }) => {
                      // Handle ::file:: links generated by processInlineFileRefs
                      if (href?.startsWith('::file::')) {
                        const file = href.replace('::file::', '');
                        return <FilePill file={file} />;
                      }
                      return (
                        <a href={href} target="_blank" rel="noopener noreferrer">
                          {children}
                        </a>
                      );
                    },
                  }}
                >
                  {processInlineFileRefs(segment.content)}
                </Md>
              </div>
            );

          case 'diff':
            return (
              <InlineDiff
                key={i}
                file={segment.file}
                lines={segment.lines}
                fileContent={files[segment.file]}
              />
            );

          case 'code':
            return (
              <InlineCode
                key={i}
                file={segment.file}
                lines={segment.lines}
                fileContent={files[segment.file]}
              />
            );

          case 'file':
            return (
              <div key={i} className="my-2">
                <FilePill file={segment.file} />
              </div>
            );

          case 'callout':
            return (
              <Callout
                key={i}
                type={segment.calloutType}
                content={segment.content}
              />
            );

          default:
            return null;
        }
      })}
    </section>
  );
}
